### ISSUE TITLE
The contents of the window will be displayed recursively

### ISSUE THREAD

**Issue by kotetz** [tksh164/displayscope#59]
This application captures the contents of the application's own window, which results in a small window recursively appearing in the window.

**Comment by tksh164** [comment]
Like this? If so, that behavior is not an issue. Displayscope shows screen include own window if you choose the screen that has Displayscope window.

Please try choose to another screen. Displayscope needs the second screen or [display emulator/display dummy plug](https://www.amazon.com/s?k=Display+Emulator).

![image](https://user-images.githubusercontent.com/1618784/105499131-5effb200-5d04-11eb-8057-e15216527f5b.png)
