### ISSUE TITLE
Always position the window in front

### ISSUE THREAD

**Issue by tsubasaxZZZ** [tksh164/displayscope#60]
I would like to have the option to "Always position the window in front".
Sometimes it's hidden by other applications window.

**Comment by tksh164** [comment]
Add in PR #61. It will be included in the next release.

![image](https://user-images.githubusercontent.com/1618784/105599877-fe41a980-5dd7-11eb-97e8-ed3d7f2b474e.png)

**Comment by tsubasaxZZZ** [comment]
Thank you for your quick update. I'm looking forward next release. The timing for closing this issue is up to you.

**Comment by tksh164** [comment]
[v0.2.0](https://github.com/tksh164/displayscope/releases/latest) is released. This release includes the always on top feature.
