### ISSUE TITLE
The right and left edges of the screen are cut off

### ISSUE THREAD

**Issue by tsubasaxZZZ** [tksh164/displayscope#63]
## actual
The right and left edges of the screen are cut off at Displayscope.
In the figure below, the maximize button of notepad is not displayed.
![image](https://user-images.githubusercontent.com/3822284/105623951-3a6d1c80-5e61-11eb-9154-a3a47899f117.png)

However, it is supposed to be displayed correctly in screen sharing. This problem seems to be only on the Displayscope preview screen.
The figure below is a recording of the No. 3(Plz see my environment) screen shared by Teams.
![image](https://user-images.githubusercontent.com/3822284/105624032-c1ba9000-5e61-11eb-97e1-d6dc8d53a1ce.png)

## environment
The following is my desktop display layout:
![image](https://user-images.githubusercontent.com/3822284/105624053-eca4e400-5e61-11eb-927f-07755c5e3a72.png)
No.3 is dummy plug display.

## repro step
1. Start Displayscope
2. Move Displayscope to No.2 display
   - ![image](https://user-images.githubusercontent.com/3822284/105624163-dd726600-5e62-11eb-8cc7-bb7f1e1641bf.png)
3. Select "Select another screen"
4. Select No.3 Display

## expected
The left and right sides are not to be cut.

**Comment by tksh164** [comment]
Thanks for your report. I confirmed the same issue in my environment. I will investigate the issue.

First investigation results (changed No.2 display's resolution and scale combination):

- The issue does **occur** if No.2 display has 1440 x 2560 resolution and 100% scale.
- The issue does **occur** if No.2 display has 1440 x 2560 resolution and 125% scale.
- The issue does **occur** if No.2 display has 1536 x 2048 resolution and 100% scale.
- The issue does **occur** if No.2 display has 1536 x 2048 resolution and 125% scale.
- The issue does **occur** if No.2 display has 1600 x 2560 resolution and 100% scale.
- The issue does **occur** if No.2 display has 1600 x 2560 resolution and 125% scale.
- The issue does **not occur** if No.2 display has 1800 x 2880 resolution and 100% scale.
- The issue does **occur** if No.2 display has 1800 x 2880 resolution and 125% scale.
- The issue does **not occur** if No.2 display has 2160 x 3840 resolution and 125% scale.
- The issue does **not occur** if No.2 display has 2160 x 3840 resolution and 100% scale.

**Comment by tksh164** [comment]
@tsubasaxZZZ The issue is no longer reproduced in my environment. But I don't know reason. Does the issue still occur after rebooting your machine?

**Comment by tsubasaxZZZ** [comment]
I have tried the latest version. After uninstalling the previous version and reinstalling it, the problem no longer reproduced (Not rebooted). So, you can close this issue. Thank you for your support.
